name: up_bus_hk_data_builder
description: A data building utility for the UpBusHK project.
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

isar_version: &isar_version 3.3.0

dependencies:
  up_bus_hk_core:
    git:
      url: git@github.com:outdoorapps/UpBusHK-core.git
      ref: main

  # Network
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  retrofit: 4.9.0 # todo do not use 4.9.1

  # Code generation
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  copy_with_extension: ^9.0.0

  # Storage
  isar_community: *isar_version

  # Parsing
  xml: ^6.6.1
  json_events: ^1.2.2
  proj4dart: ^3.0.0

  # Utils
  path: ^1.9.1
  collection: any
  synchronized: ^3.4.0
  get_it: ^9.0.5
  latlong2: ^0.9.1
  archive: ^4.0.7

# Developer-only dependencies (for testing, linting, etc.)
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

  # Code generation
  build_runner: ^2.6.0
  isar_community_generator: *isar_version
  json_serializable: ^6.11.1
  freezed: ^3.2.1
  copy_with_extension_gen: ^9.0.0
  retrofit_generator: ^10.0.1

dependency_overrides:
  analyzer: 8.3.0 # For source_gen 3.0.0

# Optional: specify an entrypoint if needed (for multiple scripts)
# executables:
#   data_builder: bin/up_bus_hk_data_builder.dart

# Prevent accidental publishing to pub.dev
publish_to: none
